version: "3.9"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: infinitymarket-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Px3!nLo8@bQcT7wZ"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'Px3!nLo8@bQcT7wZ' -Q 'SELECT 1'" ]
      interval: 10s
      retries: 10
      start_period: 30s
      timeout: 5s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: infinitymarket-app
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=InfinityMarketDB_7f2c;User Id=sa;Password=Px3!nLo8@bQcT7wZ;TrustServerCertificate=True;
    depends_on:
      sqlserver:
        condition: service_healthy

volumes:
  sqlserver_data:

