version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "InfinityStrong@2024"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    networks:
      - infinity-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S 127.0.0.1 -U sa -P InfinityStrong@2024 -Q 'SELECT 1' || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 60s

  infinity-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: infinity-market-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=InfinityMarketDb;User Id=sa;Password=InfinityStrong@2024;TrustServerCertificate=true;MultipleActiveResultSets=true"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - infinity-network
    restart: unless-stopped

networks:
  infinity-network:
    driver: bridge