name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - 'InfinityMarket.api/infinitymarket.client/**'
      - '.github/workflows/deploy-frontend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload HTML/CSS to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'InfinityMarket.api/infinitymarket.client'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4